version: "3"
services:
  # docker-compose up -d mysql
  mysql:
    container_name: mysql
    # 5.7
    image: mysql:${MYSQL_VERSION}
    environment:
      # mysql root用户密码
      MYSQL_ROOT_PASSWORD: root
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/files:/var/lib/mysql-files
    ports:
      - "1111:3306"
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:${NACOS_VERSION}
    volumes:
      # 需要添加mysql8的插件
      #- ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - ./nacos1/data:/home/nacos/data
      # 把日志文件映射出来
      - ./nacos1/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./naco_conf/nacos1.properties:/home/nacos/init.d/custom.properties

    environment: # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
      #- MODE=standalone   #单机版
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      # 集群配置文件
      - ./.env
    restart: always
    depends_on:
      - mysql
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    volumes:
      #- ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - ./nacos2/data:/home/nacos/data
      # 把日志文件映射出来
      - ./nacos2/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./naco_conf/nacos2.properties:/home/nacos/init.d/custom.properties
    environment: # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
    ports:
      - "8849:8848"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mysql
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    volumes:
      #- ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - ./nacos3/data:/home/nacos/data
      # 把日志文件映射出来
      - ./nacos3/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./naco_conf/nacos3.properties:/home/nacos/init.d/custom.properties
    environment: # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
    ports:
      - "8850:8848"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mysql
