version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ="Asia/Shanghai"
      - MYSQL_HOST=${MYSQL_HOST}
      # - MYSQL_ROOT_HOST=%
      # 登录：mysql -u tanrenjie -p'123456' -h 127.0.0.1 nest-admin
      # - MYSQL_USER=nacos
      # - MYSQL_PASSWORD=123456
    # 推荐SQL模式 sql_mode：STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
      --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    volumes:
      # mysql的数据文件
      - ./mysql/data:/var/lib/mysql
      # mysql配置文件
      - ./mysql/config:/etc/mysql/conf.d
      # # 初始化SQL脚本目录
      - ./init_sql/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:  # 新增健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:${NACOS_VERSION}
    volumes:
      # 需要添加mysql8的插件
      - ./plugins/:/home/nacos/plugins/mysql/
      # 把日志文件映射出来
      - ./nacos1/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./conf/nacos.custorm.properties:/home/nacos/init.d/custom.properties
    
    environment: # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
      #- MODE=standalone   #单机版
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
        # 集群配置文件
      - ./.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # 等待数据库健康状态
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    volumes:
      # 需要添加mysql8的插件
      - ./plugins/:/home/nacos/plugins/mysql/
      # 把日志文件映射出来
      - ./nacos1/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./conf/nacos.custorm.properties:/home/nacos/init.d/custom.properties
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
    ports:
      - "8849:8848"
    env_file:
      - ./.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # 等待数据库健康状态
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    volumes:
      # 需要添加mysql8的插件
      - ./plugins/:/home/nacos/plugins/mysql/
      # 把日志文件映射出来
      - ./nacos1/logs:/home/nacos/logs
      # 把配置文件映射出来
      - ./conf/nacos.custorm.properties:/home/nacos/init.d/custom.properties
    environment:                      # 设置环境变量,相当于docker run命令中的-e
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
    ports:
      - "8850:8848"
    env_file:
      - ./.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # 等待数据库健康状态