version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ../init_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standalone-mysql.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    # restart: always
